# Generated by Django 3.0.7 on 2020-07-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='text',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
